#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
BASH_HELPERS_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd -P)"

GIT_SNAPSHOT_GUI_TEST_DISABLE_FS_WATCH_EVENTS=1 \
GIT_SNAPSHOT_GUI_LIVE_REFRESH_FALLBACK_POLL_MS=300 \
GIT_SNAPSHOT_GUI_LIVE_REFRESH_REPO_PROBE_DEBOUNCE_MS=100 \
GIT_SNAPSHOT_GUI_LIVE_REFRESH_REPO_PROBE_THROTTLE_MS=300 \
GIT_SNAPSHOT_GUI_TEST_BROWSE_DATA_DELAY_MS=1200 \
GIT_SNAPSHOT_GUI_TEST_COMPARE_DATA_DELAY_MS=1200 \
  exec "${BASH_HELPERS_ROOT}/lib/git-snapshot/ui-tests/run-tests.sh" general-ui 12 "$@"
